### ISSUE TITLE
netburner and virtualcom

### ISSUE THREAD

**Issue by ieee488** [jlegen/Kellerklima#1]
I found your post at https://github.com/jeelabs/esp-link/issues/294

Would you explain further how you were able to flash an Arduino and an attached ESP-01 module running esp-link firmware?

**Comment by jlegen** [comment]
Uh, sorry, i did not get a notification (and did not deal with this project for some time), so i missed your question. But better late than never...

To flash an arduino (i use this with "pro minis") using ESP-Link, the simplest method is using a "virtual com port driver". Using windows, you might use one of these free drivers:
https://www.hw-group.com/software/hw-vsp3-virtual-serial-port
https://www.netburner.com/virtual-com-port/
They create additional "com ports" (serial ports), e.g. "Com10". They provide a little config window, where you have to enter the IP address and the port of your ESP-Link-module.
For local access/development that's the IP address the router gave the ESP-link (like 192.168.1.55), and the port is "2323".
Then simply chose "com10" in Arduino-IDE for "Upload", and that's it. 
I even use this to update units "in the field" (at other locations), using DynamicDNS-IPs - works as well, but should not be left "open" by default...

**Comment by ieee488** [comment]
Thank you for the answer!

The link for the Netburner driver is https://www.netburner.com/download/virtual-comm-port-driver-windows-xp-10/

The drivers will be useful.

.
